name: Sync Docs and Create PR

on:
  schedule:
    - cron: '0 0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-sync:
    runs-on: ubuntu-latest
    permissions:
      # Required to checkout the code, create a branch, and push changes
      contents: write
      # Required to create a pull request
      pull-requests: write

    steps:
      - name: Install latest oxipng from GitHub Releases
        run: |
          echo "Fetching latest oxipng version from GitHub API..."
          OXIPNG_VERSION=$(curl -s "https://api.github.com/repos/shssoichiro/oxipng/releases/latest" | grep -Po '"tag_name": "v\K[0-9.]+')
          
          if [ -z "$OXIPNG_VERSION" ]; then
            echo "::error::Could not determine latest oxipng version. Exiting."
            exit 1
          fi
          
          echo "Latest version found: v$OXIPNG_VERSION"
          URL="https://github.com/shssoichiro/oxipng/releases/download/v${OXIPNG_VERSION}/oxipng-v${OXIPNG_VERSION}-x86_64-unknown-linux-musl.tar.gz"
          
          echo "Downloading oxipng from $URL"
          curl -L $URL | tar -xz
          
          echo "Installing oxipng to /usr/local/bin"
          sudo mv oxipng-v${OXIPNG_VERSION}-x86_64-unknown-linux-musl/oxipng /usr/local/bin/
          
          echo -n "Verifying installation: "
          oxipng --version

      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Define folders to sync
        id: folders
        run: echo "list=flex-manual hepa-uv pd-manual shared stacker-manual thermocycler-manual" >> $GITHUB_OUTPUT

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Clean up old docs directory
        run: rm -rf docs

      - name: Download specific doc folders
        run: |
          SPARSE_PATHS=$(for folder in ${{ steps.folders.outputs.list }}; do echo "docs/$folder"; done)
          echo "Setting up sparse checkout for:"
          echo "$SPARSE_PATHS"
          git clone --depth 1 --filter=blob:none --sparse --branch edge https://github.com/Opentrons/opentrons.git opentrons-temp
          cd opentrons-temp
          git sparse-checkout set $SPARSE_PATHS
          mkdir -p ../docs
          mv docs/* ../docs/
          cd ..
          rm -rf opentrons-temp

      - name: Optimize images and clean up build files
        run: |
          TARGET_DIR="docs"
          if [ ! -d "$TARGET_DIR" ]; then
            echo "Target directory '$TARGET_DIR' not found. Skipping."
            exit 0
          fi
          echo "Removing mkdocs.yml files..."
          find $TARGET_DIR -name "mkdocs.yml" -type f -delete
          echo "Optimizing PNGs..."
          find $TARGET_DIR -name "*.png" -type f -exec oxipng -o 4 --strip safe {} +
          echo "Optimization complete."

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "docs: Sync and optimize docs for ${{ steps.date.outputs.date }}"
          branch: "docs/auto-sync"
          delete-branch: true
          title: "Automated Docs Sync (${{ steps.date.outputs.date }})"
          body: |
            This is an automated PR to sync the latest documentation from the Opentrons repository.

            The following folders have been updated:
            * `${{ steps.folders.outputs.list }}`

            Please review the changes and merge if they are correct.
          labels: documentation, automated
          assignees: koji

      - name: Output PR URL
        run: echo "Pull Request URL: ${{ steps.cpr.outputs.pull-request-url }}"